### PR TITLE
Make installGithub.r script not use devtools

### PR DESCRIPTION
**Pull request by cboettig**
devtools is a big install with lots of dependencies, so this changes installGithub.r to use the lightweight [remotes](https://cran.r-project.org/web/packages/remotes/index.html) instead which should provide equivalent functionality. 

I've also taken the liberty to add `remotes` to the Suggests list.

### CODE REVIEW

**Comment by cboettig** [comment]
Whoops, sorry about that failing travis check, didn't realize you were still using a `c` based travis with manual install.  Would you prefer I modify the existing travis (not sure if r-cran-remotes is in the debian repo travis is using) or just switch it out for the new R travis file (which should automatically install all the R packages listed in Suggests)?

**Comment by eddelbuettel** [comment]
(Aside: Apart from remotes there is also (at least) ghit.  We should find something.)

As you noticed, my Travis setup lives off things in .deb packages, and devtools is a given there.  So <shrug>.  That cost is really amortized.  Whereas remotes is a fresh new cost.  Worth it?   Not sure.

Then again, the littler _scripts_ are all in in examples and neither devtools nor remotes has to be in Suggests.  Can you try (locally first) to just not use Suggests:  ?

**Comment by eddelbuettel** [comment]
Yes, tested locally here.  Please alter the PR to do:

a) no change to DESCRIPTION; we can leave that for another time
b) in `installGithub.r` switch the package load

et voila

```bash
~/git/littler(master)$ git diff inst/examples/installGithub.r
diff --git a/inst/examples/installGithub.r b/inst/examples/installGithub.r
index 97f611e..8523774 100755
--- a/inst/examples/installGithub.r
+++ b/inst/examples/installGithub.r
@@ -8,7 +8,8 @@
 
 ## load docopt and devtools from CRAN
 suppressMessages(library(docopt))       # we need docopt (>= 0.3) as on CRAN
-suppressMessages(library(devtools)) 
+#suppressMessages(library(devtools)) 
+suppressMessages(library(remotes)) 
 
 ## configuration for docopt
 doc <- "Usage: installGithub.r [-h] [-x] [-d DEP
~/git/littler(master)$ 
```

**Comment by eddelbuettel** [comment]
Or for that matter just close the PR and I commit this...

**Comment by cboettig** [comment]
sounds like a plan.

**Comment by eddelbuettel** [comment]
Now I don't _use_ remotes.  It is a plugin replacement and "just works" ?

**Comment by cboettig** [comment]
yes, it's Gabor's creation but basically just rips the `install_github()` function from devtools and makes it stand by itself.  (needs only `methods`, `utils`, and a system installation of `git`). Gabor's been good about actively maintaining his packages so I think "just works" is a safe assumption.  

Right, `devtools` is on travis systems, but it's not in, say, `r-base`, even though we link `installGithub` script.

**Comment by eddelbuettel** [comment]
Yes, perfect.  I did bite the bullet for one or two of packages and debianized some of his packages (via my own Launchpad PPA which my (forked, maintained) r-travis goes to) so I could even do this for remotes.

But it looks like `inst/examples/` is enough to trick `R CMD check` into not seeing it :)   Once I want the CRAN package to be "proper" a Suggests is probably warranted and I may then just spend the 10 minutes to make a .deb for remotes...

How do you "consume" littler now for Docker?  Do you need it updated on CRAN "soon" ?

**Comment by cboettig** [comment]
nope, either is fine

**Comment by eddelbuettel** [comment]
Cool. And I just did a recursive grep (or, rather, `ag`) and devtools is currently in the vignette as well.  So I guess I need to clean that up more thoroughly.

On the TODO list ...

**Comment by eddelbuettel** [comment]
See my PR #44 which I just merged.   Basically what you attempted but over more (code) files yet leaving DESCRIPTION alone.

I may add one or two new helpers and ship.  Among the helper that is coming is something simple based on your Dockerfile snippets to get the .deb files off RStudio's website.

**Pull request closed without merging**
