### PR TITLE
feat: Add basic pre-commit hooks

### PR DESCRIPTION
**Pull request by datawookie**
Hi!

I've added some basic pre-commit hooks. We are using these on all of our R projects and find that they contribute significantly to code quality. I only added some basic hooks and then applied them to the project. I know that a lot of files were changed but you should find that all of the changes were cosmetic.

Best regards, Andrew.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
You just proposed a PR, without discussion, that touches 122 files.  One hundred and twelve.  I don't think I want to go there.

**Comment by datawookie** [comment]
No problem. Although I should point out that 122 != one hundred and twelve.

**Comment by eddelbuettel** [comment]
Corrected typo.  Also, I happen to really dislike the output from `styler`.  Sorry.

**Comment by datawookie** [comment]
Haha. No worries. It's not for everyone!

**Comment by eddelbuettel** [comment]
(As a finaly comment, you brutishly ran your filter over autogenerated documentation too.  A whitelist may have helped a little, and it would likely have cut down significantly on the number of files.  But as I said, I don't like the proposed style, I like the indendation scheme I just for 30 or so years across several programming language -- so it'll be a no.  Sorry.  I am sure you meant well.)

**Comment by datawookie** [comment]
>  I am sure you meant well.

I surely did.

This is a great tool, which we use routinely. I'll make a more considered contribution in future.

**Pull request closed without merging**
