### PR TITLE
feat: add -n argument to installGithub.r like install2.r

### PR DESCRIPTION
**Pull request by atusy**
I wanted parallel installing of packages also in installGithub.r, and implemented it just like install2.r.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
You know I looked at that too for the basic `install.r` I still use a lot.  And this is very similar: I am not sure that just adding 

```
invisible(sapply(opt$GHREPOS, function(r) install_github(r, dependencies = opt$deps, \
                  upgrade = opt$update, repos = opt$repos, Ncpus = opt$ncpus)))
```

here works because of the `sapply` puts us on the wrong track.  It is still a serial loop. 

And for `install.r` I didn't want to switch to add-on packages / didn't feel like mucking with eg `parallel::mclappy`.  Can you demonstrate that this actually installs in parallel?  I would think it does not.

So here you may only pass `Ncpus` down to the install_github()`

**Comment by atusy** [comment]
`install_github` passes `...` to `utils::install.packages()` as described in document.

https://github.com/r-lib/remotes/blob/1f657ec067088add76adedfcc9a0ea2a45aac9e9/inst/install-github.R#L2345

It should be noted that `repo` will be transformed to `remotes` and then applied to `install_remote` with `vapply`.
This means there are no ways to install multiple repositories simultaneously.
Yet, it is still possible to install dependencies of each repositories simultaneously.

Here's an activity diagram of `install_github` and I confirmed `...` is actually passed to `utils::install.packages()`

image

**Comment by eddelbuettel** [comment]
I think you missed the fact that we have an _outer_ sapply around it feeding _each argument individually_ to the function.  Look at the last line of the existing function, and/or you modified function.

As we are feeding arguments one-by-one, there cannot be parallel processing of several at once.

**Comment by atusy** [comment]
Yes, I understand, and that's what I mentioned in

> It should be noted that repo will be transformed to remotes and then applied to install_remote with vapply, and a similar thing is explicitly done by sapply in the code mentioned in your reply.
This means there are no ways to install multiple repositories simultaneously.
Yet, it is still possible and helpful to install dependencies of each repositories simultaneously.

Let's say installing A and B from GitHub and A has dependencies A1, A2, A3, ... and B has dependencies B1, B2, B3, ....

There is no way to install A and B simultaneously, but still A1, A2, A3, ... can be installed simultaneously and B1, B2, B3, ... as well.

**Comment by eddelbuettel** [comment]
I think I understand what you are trying to get at, but I am trying to explain that you it cannot possibly work as long as _each invocation of the function is separate and on a single argument_.   

Just put some inner `print` statements to convince yourself.

**Comment by atusy** [comment]
Looks like you are right...
I compared installing order of packages for tidyverse when n = 1 and n = 8.
The result looks same.
I'll be back if I find any way to install in parallel.

**Comment by eddelbuettel** [comment]
> I'll be back if I find any way to install in parallel.

Yes, I am (casually) looking at that for `install.r` as well (which is harder as it has no Depends:, and should not have any).  There I may have to find a cheap way to reorganise arguments to pass a vector on have the (now explicit) looping done implicitly by `install.packages()` which could then use parallelism.  

It is the same issue here.  It may need a rewrite, and so it may just be easiest to for now write a local helper script at your end, and over time and from testing it see if it would be worth including here.

**Comment by eddelbuettel** [comment]
@atusy I just committed [installParallel.r](https://github.com/eddelbuettel/littler/blob/master/inst/examples/installParallel.r) -- it generalizes `install.r` and may replace it in the next version.  In essence, it checks all supplied arguments and if none are local files in can in effect install using `n > 1` by passing the argument to `install.packages()` (and setting `n`).   You _could_ try to do something similar for the `remotes::install_github()` call.  Personally, I don't install much from github, and don't think I actually ever needed more than one at once.  But if you still have that itch to scratch, that may be one way.

**Comment by atusy** [comment]
Good news! I'll take a look at it!

**Comment by eddelbuettel** [comment]
The (currently named `installParallel.r`, likely to become `install.r` by release) works well.  `Ncpu` is a good option to have.  We're not in a rush -- work on it, try to test all corner cases and we go from there.

**Pull request closed without merging**
